name: Run Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: sound-ci-helper
      uses: LABSN/sound-ci-helpers@v1.0.3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pygame
        sudo apt install ffmpeg

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

    - name: Run tests
      run: |
        pytest
